# Your Solution# Book Catalog Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722week8e3.azurecr.io/projectpart5-book_catalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://projectpart5_oj1l_user:rTcxCejqzCiPrAkVwqYOWJDuBt7ZFHoA@dpg-crglns68ii6s73c4tpv0-a.oregon-postgres.render.com/projectpart5_oj1l"

# Book Catalog Service
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

# Inventory Management Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit722week8e3.azurecr.io/projectpart5-inventory_management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://projectpart5_oj1l_user:rTcxCejqzCiPrAkVwqYOWJDuBt7ZFHoA@dpg-crglns68ii6s73c4tpv0-a.oregon-postgres.render.com/projectpart5_oj1l"

# Inventory Management Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: LoadBalancer
