name: Terraform Build and Secrets Output (deprecated)

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init, Plan, and Apply followins which take relevant values and create Github Secrets
    runs-on: ubuntu-latest

    # Environment variables for Terraform and Azure
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    # Step 4: Terraform Init (initializes the working directory)
    - name: Terraform Init
      working-directory: ./scripts/terraform # Replace with your folder path
      run: terraform init

    # Step 5: Terraform Plan (show changes without applying)
    - name: Terraform Plan
      working-directory: ./scripts/terraform
      run: terraform plan

    # Step 6: Terraform Apply (apply changes if required)
    - name: Terraform Apply
      working-directory: ./scripts/terraform
      run: terraform apply -auto-approve

    # Step 7: Retrieve Terraform Outputs
    - name: Get Terraform Outputs
      id: outputs
      working-directory: ./scripts/terraform
      run: |
        echo "acr_login_url=$(terraform output -raw acr_login_url | grep -v "::debug")" >> $GITHUB_ENV
        echo "acr_username=$(terraform output -raw acr_username | grep -v "::debug")" >> $GITHUB_ENV
        echo "acr_password=$(terraform output -raw acr_password | grep -v "::debug")" >> $GITHUB_ENV
        echo "aks_kubeconfig=$(terraform output -raw aks_kubeconfig | grep -v "::debug")" >> $GITHUB_ENV

    # Step 8: Install GitHub CLI
    - name: Install GitHub CLI
      run: sudo apt-get install gh

    # Step 9: Authenticate GitHub CLI
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.SECRETS_MODIFY_TOKEN }}" | gh auth login --with-token

    # Step 10: Create GitHub Secrets from Outputs
    - name: Create GitHub Secrets
      run: |
        echo "Creating or updating secrets in GitHub repository"

        gh secret set CONTAINER_REGISTRY -b "${{ env.acr_login_url }}"
        gh secret set REGISTRY_UN -b "${{ env.acr_username }}"
        gh secret set REGISTRY_PW -b "${{ env.acr_password }}"
        gh secret set KUBE_CONFIG -b "${{ env.aks_kubeconfig }}"
